# Generated by Django 5.0.6 on 2026-01-05 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_meals', models.IntegerField(blank=True, default=3)),
                ('meal_description', models.CharField(blank=True, max_length=50)),
                ('avg_mood', models.IntegerField(default=5)),
                ('satiation_level', models.IntegerField(default=5)),
                ('exercise_amount_hr', models.IntegerField(blank=True, default=5)),
                ('post_meal_notes', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
