STATE_PROFILES = {
    0: {  #stable
        "urge_intensity": (2, 0.8),
        "binge_urge": (1, 0.5),
        "restriction_urge": (3, 0.7),
        "emotional_distress": (2, 0.6),
        "stress_level": (3, 0.8),
        "energy_level": (7, 0.9),
        "sleep_hours": (7.5, 0.7),
        "num_meals": (3, 0.5),
        "exercise_minutes": (30, 15),
    },
    1: {  #emotional distress + restriction
        "urge_intensity": (6, 1.0),
        "binge_urge": (2, 0.7),
        "restriction_urge": (9, 0.8),
        "emotional_distress": (9, 0.6),
        "stress_level": (8, 0.7),
        "energy_level": (4, 0.9),
        "sleep_hours": (8.5, 1.0),
        "num_meals": (1.5, 0.6),
        "exercise_minutes": (45, 20),
    },
    2: {  #emotional distress + binge
        "urge_intensity": (7, 1.0),
        "binge_urge": (8, 0.9),
        "restriction_urge": (3, 0.8),
        "emotional_distress": (7, 0.7),
        "stress_level": (8, 0.7),
        "energy_level": (6, 1.0),
        "sleep_hours": (4.5, 0.6),
        "num_meals": (5, 0.7),
        "exercise_minutes": (25, 15),
    },
    3: {  #burnout/numb
        "urge_intensity": (4, 0.9),
        "binge_urge": (3, 0.8),
        "restriction_urge": (3, 0.7),
        "emotional_distress": (4, 0.8),
        "stress_level": (5, 0.8),
        "energy_level": (2, 0.6),
        "sleep_hours": (6, 1.2),
        "num_meals": (2.5, 0.6),
        "exercise_minutes": (10, 10),
    }
}

STATE_PROFILES_TEST = {
    0: {  #stable
        "urge_intensity": (2, 0.7),
        "binge_urge": (2, 0.7),
        "restriction_urge": (3, 0.6),
        "emotional_distress": (2, 0.6),
        "stress_level": (3, 0.8),
        "energy_level": (8, 0.7),
        "sleep_hours": (8, 1.0),
        "num_meals": (3, 0.8),
        "exercise_minutes": (45, 15),
    },
    1: {  #emotional distress + restriction
        "urge_intensity": (7, 1.2),
        "binge_urge": (2, 0.6),
        "restriction_urge": (9, 1.2),
        "emotional_distress": (9, 0.7),
        "stress_level": (8, 1),
        "energy_level": (4, 0.9),
        "sleep_hours": (8, 1.0),
        "num_meals": (1.5, 0.6),
        "exercise_minutes": (45, 25),
    },
    2: {  #emotional distress + binge
        "urge_intensity": (7, 1.0),
        "binge_urge": (9, 0.9),
        "restriction_urge": (3, 0.9),
        "emotional_distress": (8, 0.7),
        "stress_level": (9, 0.9),
        "energy_level": (5, .9),
        "sleep_hours": (4, 0.6),
        "num_meals": (5, 0.7),
        "exercise_minutes": (25, 10),
    },
    3: {  #burnout/numb
        "urge_intensity": (2, 0.7),
        "binge_urge": (3, 0.7),
        "restriction_urge": (2, 0.6),
        "emotional_distress": (4, 0.8),
        "stress_level": (6, 0.9),
        "energy_level": (2, 0.6),
        "sleep_hours": (6, 1.2),
        "num_meals": (2, 0.6),
        "exercise_minutes": (10, 10),
    }
}

