# Generated by Django 5.0.6 on 2026-08-21 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('base', models.CharField(blank=True, default='', max_length=32)),
                ('protein', models.CharField(blank=True, default='', max_length=32)),
                ('colorful', models.CharField(blank=True, default='', max_length=32)),
                ('sauce', models.CharField(blank=True, default='', max_length=32)),
                ('extra', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='built_meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExplorerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_id', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('tried_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explorer_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tried_at'],
            },
        ),
    ]
