# Generated by Django 5.0.6 on 2025-11-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
