# Generated by Django 5.0.6 on 2025-11-17 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='title',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
