# Generated by Django 5.0.6 on 2026-05-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_journalentry_mood_remove_journalentry_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry',
            field=models.TextField(max_length=1000),
        ),
    ]
