# Generated by Django 5.0.6 on 2026-08-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_journalentry_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='distortion_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('prompted', 'Prompted'), ('free_write', 'Free Write')], default='prompted', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
