# Generated by Django 5.0.6 on 2025-11-25 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='title',
        ),
        migrations.AddField(
            model_name='assessment',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
