# Generated by Django 5.0.6 on 2025-12-04 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_description', models.CharField(blank=True, max_length=10)),
                ('meal_type', models.CharField(blank=True, max_length=10)),
                ('time', models.DateTimeField(auto_now=True)),
                ('mood_before', models.JSONField(blank=True, default=list)),
                ('mood_after', models.JSONField(blank=True, default=list)),
                ('hunger_level', models.IntegerField(default=3)),
                ('post_meal_notes', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
