# Generated by Django 5.0.6 on 2026-05-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='action_type',
            field=models.CharField(max_length=100),
        ),
    ]
