# Generated by Django 5.0.6 on 2026-05-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_alter_pointtransaction_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
