# Generated by Django 5.0.6 on 2026-01-27 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urge_intensity', models.IntegerField(blank=True, default=5)),
                ('binge_urge', models.IntegerField(blank=True, default=5)),
                ('restriction', models.IntegerField(blank=True, default=5)),
                ('emotional_distress', models.IntegerField(blank=True, default=5)),
                ('stress_level', models.IntegerField(blank=True, default=5)),
                ('energy_level', models.IntegerField(blank=True, default=5)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
