# Generated by Django 5.0.6 on 2026-01-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelog', '0002_carelog_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelog',
            name='state_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
