# Generated by Django 5.0.6 on 2026-02-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelog', '0003_carelog_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelog',
            name='exercise_minutes',
            field=models.IntegerField(blank=True, default=30),
        ),
        migrations.AddField(
            model_name='carelog',
            name='num_meals',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AddField(
            model_name='carelog',
            name='sleep_hours',
            field=models.IntegerField(blank=True, default=7),
        ),
    ]
