# Generated by Django 5.0.6 on 2026-02-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelog', '0004_carelog_exercise_minutes_carelog_num_meals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carelog',
            name='num_meals',
            field=models.FloatField(blank=True, default=3.0),
        ),
        migrations.AlterField(
            model_name='carelog',
            name='sleep_hours',
            field=models.FloatField(blank=True, default=7.0),
        ),
    ]
