# Generated by Django 5.0.6 on 2026-05-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelog', '0005_alter_carelog_num_meals_alter_carelog_sleep_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carelog',
            name='notes',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
