# Generated by Django 5.0.6 on 2026-08-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelog', '0007_alter_carelog_float_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelog',
            name='distortion_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='carelog',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carelog',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='carelog',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
