# Generated by Django 5.0.6 on 2026-06-16 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='images',
        ),
        migrations.CreateModel(
            name='QuestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/quest_images/')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quests.quest')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestImages',
        ),
    ]
