import Colors from "../constants/colors";

const DAILY_ACTIVITIES = [
  {
    id: "carelog",
    title: "Care Log",
    description: "Gently observe yourself and your habits.",
    color: Colors.greyish,
    border: Colors.lightCoffeeBrown,
    fontColor: Colors.lightCoffeeBrown,
    img: require("../assets/icons/newwaves.png"),
    //screen: "Tracking",
    screen: "Assessment",
  },
  {
    id: "quests",
    title: "Quests",
    description: "Challenge yourself and your mind by completing quests.",
    //color: Colors.pastelBlue,
    //border: Colors.darkBlue,
    color: Colors.greyish,
    border: Colors.seaDarkBlue,
    fontColor: Colors.darkBlueText,
    img: require("../assets/icons/shell.png"),
    imgColor: Colors.darkBlueText,
    screen: "Quests",
  },
  /*{
    id: "chat",
    title: "Chatroom",
    description: "Have a chat with Izzy on eating disorders and nutrition.",
    color: Colors.greyish,
    border: Colors.secondMarineBlue,
    fontColor: Colors.secondMarineBlue,
    img: require("../assets/pinkbubbleoutline.png"),
    screen: "Chatbot",
  },
  {
    id: "stickers",
    title: "Stickers",
    description: "Earn stickers for showing up!",
    color: Colors.greyish,
    border: Colors.lightCoffeeBrown,
    fontColor: Colors.lightCoffeeBrown,
    img: require("../assets/icons/waves.png"),
    //screen: "Tracking",
    screen: "StickersScreen",
  },*/
  {
    id: "journal",
    title: "Journal",
    description: "Set your thoughts and feelings free by journaling.",
    color: Colors.greyish,
    border: Colors.lightCoffeeBrown,
    fontColor: Colors.darkBrownText,
    img: require("../assets/icons/beachball.png"),
    imgColor: Colors.darkBrownText,
    screen: "Journal",
  },
  {
    id: "quickReads",
    title: "Quick Reads",
    description: "Learn about eating disorders, nutrition, and sport science!",
    color: Colors.greyish,
    border: Colors.seaBlue2,
    fontColor: Colors.darkBlueText,
    img: require("../assets/icons/umbrella.png"),
    imgColor: Colors.darkBlueText,
    screen: "QuickReadsList",
  },
];

export { DAILY_ACTIVITIES };
